// Market universe (Yahoo tickers) + sample portfolio for the risk gauge.
export interface SymbolDef { symbol: string; name: string; }

export const MARKET_GROUPS: Record<string, SymbolDef[]> = {
  "Índices US": [
    { symbol: "^GSPC", name: "S&P 500" }, { symbol: "^NDX", name: "Nasdaq 100" },
    { symbol: "^IXIC", name: "Nasdaq Composite" }, { symbol: "^DJI", name: "Dow Jones" },
    { symbol: "^RUT", name: "Russell 2000" }, { symbol: "^OEX", name: "S&P 100" },
    { symbol: "^MID", name: "S&P MidCap 400" }, { symbol: "^SP600", name: "S&P SmallCap 600" },
    { symbol: "^SOX", name: "Semiconductors (PHLX)" }, { symbol: "^NYA", name: "NYSE Composite" },
    { symbol: "^VIX", name: "VIX (volatility)" }, { symbol: "^TNX", name: "US 10Y Treasury (yield)" },
  ],
  "Índices Globais": [
    { symbol: "^FTSE", name: "FTSE 100 (UK)" }, { symbol: "^GDAXI", name: "DAX (Germany)" },
    { symbol: "^FCHI", name: "CAC 40 (France)" }, { symbol: "^STOXX50E", name: "Euro Stoxx 50" },
    { symbol: "^IBEX", name: "IBEX 35 (Spain)" }, { symbol: "^N225", name: "Nikkei 225 (Japan)" },
    { symbol: "^HSI", name: "Hang Seng (HK)" }, { symbol: "000001.SS", name: "Shanghai Composite" },
    { symbol: "^KS11", name: "KOSPI (Korea)" }, { symbol: "^TWII", name: "Taiwan Weighted" },
    { symbol: "^BSESN", name: "SENSEX (India)" }, { symbol: "^AXJO", name: "ASX 200 (Australia)" },
    { symbol: "^GSPTSE", name: "TSX (Canada)" }, { symbol: "^BVSP", name: "Ibovespa (Brazil)" },
    { symbol: "^MXX", name: "IPC (Mexico)" },
  ],
  "ETFs": [
    { symbol: "SPY", name: "SPDR S&P 500" }, { symbol: "QQQ", name: "Invesco Nasdaq 100" },
    { symbol: "IWM", name: "iShares Russell 2000" }, { symbol: "DIA", name: "SPDR Dow Jones" },
    { symbol: "VTI", name: "Vanguard Total Market" }, { symbol: "GLD", name: "SPDR Gold" },
    { symbol: "SLV", name: "iShares Silver" }, { symbol: "TLT", name: "iShares 20+Y Treasury" },
    { symbol: "IEF", name: "iShares 7-10Y Treasury" }, { symbol: "HYG", name: "iShares High Yield" },
    { symbol: "LQD", name: "iShares IG Corp" }, { symbol: "AGG", name: "iShares US Aggregate" },
    { symbol: "EEM", name: "iShares Emerging Mkts" }, { symbol: "EFA", name: "iShares EAFE" },
    { symbol: "VEA", name: "Vanguard Developed" }, { symbol: "VWO", name: "Vanguard Emerging" },
    { symbol: "SMH", name: "VanEck Semiconductors" }, { symbol: "SOXX", name: "iShares Semiconductors" },
    { symbol: "ARKK", name: "ARK Innovation" }, { symbol: "KWEB", name: "China Internet" },
    { symbol: "VNQ", name: "Vanguard Real Estate" }, { symbol: "USO", name: "US Oil Fund" },
  ],
  "Ações": [
    { symbol: "MU", name: "Micron Technology, Inc." }, { symbol: "NVDA", name: "NVIDIA Corporation" }, { symbol: "AAPL", name: "Apple Inc." },
    { symbol: "TSLA", name: "Tesla, Inc." }, { symbol: "MSFT", name: "Microsoft Corporation" }, { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
    { symbol: "INTC", name: "Intel Corporation" }, { symbol: "AMZN", name: "Amazon.com, Inc." }, { symbol: "AVGO", name: "Broadcom Inc." },
    { symbol: "GOOGL", name: "Alphabet Inc." }, { symbol: "META", name: "Meta Platforms, Inc." }, { symbol: "GOOG", name: "Alphabet Inc." },
    { symbol: "AMAT", name: "Applied Materials, Inc." }, { symbol: "WDC", name: "Western Digital Corporation" }, { symbol: "TSM", name: "Taiwan Semiconductor Manufactur" },
    { symbol: "ORCL", name: "Oracle Corporation" }, { symbol: "PLTR", name: "Palantir Technologies Inc." }, { symbol: "LRCX", name: "Lam Research Corporation" },
    { symbol: "QCOM", name: "QUALCOMM Incorporated" }, { symbol: "STX", name: "Seagate Technology Holdings PLC" }, { symbol: "LLY", name: "Eli Lilly and Company" },
    { symbol: "NFLX", name: "Netflix, Inc." }, { symbol: "CAT", name: "Caterpillar, Inc." }, { symbol: "KLAC", name: "KLA Corporation" },
    { symbol: "GLW", name: "Corning Incorporated" }, { symbol: "HOOD", name: "Robinhood Markets, Inc." }, { symbol: "CSCO", name: "Cisco Systems, Inc." },
    { symbol: "TXN", name: "Texas Instruments Incorporated" }, { symbol: "NOW", name: "ServiceNow, Inc." }, { symbol: "JPM", name: "JP Morgan Chase & Co." },
    { symbol: "CRM", name: "Salesforce, Inc." }, { symbol: "IBM", name: "International Business Machines" }, { symbol: "V", name: "Visa Inc." },
    { symbol: "UNH", name: "UnitedHealth Group Incorporated" }, { symbol: "WMT", name: "Walmart Inc." }, { symbol: "BRK-B", name: "Berkshire Hathaway Inc. New" },
    { symbol: "GS", name: "Goldman Sachs Group, Inc. (The)" }, { symbol: "PANW", name: "Palo Alto Networks, Inc." }, { symbol: "XOM", name: "Exxon Mobil Corporation" },
    { symbol: "SMCI", name: "Super Micro Computer, Inc." }, { symbol: "COST", name: "Costco Wholesale Corporation" }, { symbol: "COHR", name: "Coherent Corp." },
    { symbol: "ADI", name: "Analog Devices, Inc." }, { symbol: "TER", name: "Teradyne, Inc." }, { symbol: "MA", name: "Mastercard Incorporated" },
    { symbol: "BAC", name: "Bank of America Corporation" }, { symbol: "JNJ", name: "Johnson & Johnson" }, { symbol: "AAL", name: "American Airlines Group, Inc." },
    { symbol: "ABBV", name: "AbbVie Inc." }, { symbol: "CIEN", name: "Ciena Corporation" }, { symbol: "C", name: "Citigroup, Inc." },
    { symbol: "ADBE", name: "Adobe Inc." }, { symbol: "GE", name: "GE Aerospace" }, { symbol: "HD", name: "Home Depot, Inc. (The)" },
    { symbol: "INTU", name: "Intuit Inc." }, { symbol: "UBER", name: "Uber Technologies, Inc." }, { symbol: "AZO", name: "AutoZone, Inc." },
    { symbol: "CVX", name: "Chevron Corporation" }, { symbol: "MPWR", name: "Monolithic Power Systems, Inc." }, { symbol: "KO", name: "Coca-Cola Company (The)" },
    { symbol: "ON", name: "ON Semiconductor Corporation" }, { symbol: "ACN", name: "Accenture plc" }, { symbol: "SATS", name: "EchoStar Corporation" },
    { symbol: "APH", name: "Amphenol Corporation" }, { symbol: "MRK", name: "Merck & Company, Inc." }, { symbol: "BKNG", name: "Booking Holdings Inc. Common St" },
    { symbol: "SOFI", name: "SoFi Technologies, Inc." }, { symbol: "BABA", name: "Alibaba Group Holding Limited" }, { symbol: "PG", name: "Procter & Gamble Company (The)" },
    { symbol: "MS", name: "Morgan Stanley" }, { symbol: "COIN", name: "Coinbase Global, Inc." }, { symbol: "BA", name: "Boeing Company (The)" },
    { symbol: "HON", name: "Honeywell International Inc." }, { symbol: "PEP", name: "Pepsico, Inc." }, { symbol: "T", name: "AT&T Inc." },
    { symbol: "ANET", name: "Arista Networks, Inc." }, { symbol: "LIN", name: "Linde plc" }, { symbol: "VZ", name: "Verizon Communications Inc." },
    { symbol: "MCD", name: "McDonald's Corporation" }, { symbol: "WFC", name: "Wells Fargo & Company" }, { symbol: "MCHP", name: "Microchip Technology Incorporat" },
    { symbol: "ABT", name: "Abbott Laboratories" }, { symbol: "PFE", name: "Pfizer, Inc." }, { symbol: "GILD", name: "Gilead Sciences, Inc." },
    { symbol: "TMUS", name: "T-Mobile US, Inc." }, { symbol: "CME", name: "CME Group Inc." }, { symbol: "NKE", name: "Nike, Inc." },
    { symbol: "DIS", name: "Walt Disney Company (The)" }, { symbol: "TMO", name: "Thermo Fisher Scientific Inc" }, { symbol: "SCHW", name: "Charles Schwab Corporation (The" },
    { symbol: "CDNS", name: "Cadence Design Systems, Inc." }, { symbol: "AMGN", name: "Amgen Inc." }, { symbol: "ISRG", name: "Intuitive Surgical, Inc." },
    { symbol: "AXP", name: "American Express Company" }, { symbol: "FTNT", name: "Fortinet, Inc." }, { symbol: "NEE", name: "NextEra Energy, Inc." },
    { symbol: "TJX", name: "TJX Companies, Inc. (The)" }, { symbol: "ETN", name: "Eaton Corporation, PLC" }, { symbol: "SNPS", name: "Synopsys, Inc." },
    { symbol: "PWR", name: "Quanta Services, Inc." }, { symbol: "FIX", name: "Comfort Systems USA, Inc." }, { symbol: "BSX", name: "Boston Scientific Corporation" },
    { symbol: "BIL", name: "State Street SPDR Bloomberg 1-3" }, { symbol: "RTX", name: "RTX Corporation" }, { symbol: "SPGI", name: "S&P Global Inc." },
    { symbol: "FCX", name: "Freeport-McMoRan, Inc." }, { symbol: "COF", name: "Capital One Financial Corporati" }, { symbol: "CMCSA", name: "Comcast Corporation" },
    { symbol: "PM", name: "Philip Morris International Inc" }, { symbol: "NEM", name: "Newmont Corporation" }, { symbol: "MDT", name: "Medtronic plc." },
    { symbol: "SHW", name: "Sherwin-Williams Company (The)" }, { symbol: "COP", name: "ConocoPhillips" }, { symbol: "BLK", name: "BlackRock, Inc." },
    { symbol: "DE", name: "Deere & Company" }, { symbol: "MCK", name: "McKesson Corporation" }, { symbol: "SLB", name: "SLB Limited" },
    { symbol: "CVS", name: "CVS Health Corporation" }, { symbol: "VRTX", name: "Vertex Pharmaceuticals Incorpor" }, { symbol: "F", name: "Ford Motor Company" },
    { symbol: "VLO", name: "Valero Energy Corporation" }, { symbol: "SYK", name: "Stryker Corporation" }, { symbol: "CMI", name: "Cummins Inc." },
    { symbol: "RCL", name: "Royal Caribbean Cruises Ltd." }, { symbol: "SBUX", name: "Starbucks Corporation" }, { symbol: "FDX", name: "FedEx Corporation" },
    { symbol: "WELL", name: "Welltower Inc." }, { symbol: "ROST", name: "Ross Stores, Inc." }, { symbol: "HLT", name: "Hilton Worldwide Holdings Inc." },
    { symbol: "BMY", name: "Bristol-Myers Squibb Company" }, { symbol: "DHR", name: "Danaher Corporation" }, { symbol: "PGR", name: "Progressive Corporation (The)" },
    { symbol: "STRL", name: "Sterling Infrastructure, Inc." }, { symbol: "CVNA", name: "Carvana Co." }, { symbol: "AEP", name: "American Electric Power Company" },
    { symbol: "ORLY", name: "O'Reilly Automotive, Inc." }, { symbol: "NU", name: "Nu Holdings Ltd." }, { symbol: "CCL", name: "Carnival Corporation Ltd." },
    { symbol: "PYPL", name: "PayPal Holdings, Inc." }, { symbol: "GM", name: "General Motors Company" }, { symbol: "ICE", name: "Intercontinental Exchange Inc." },
    { symbol: "UNP", name: "Union Pacific Corporation" }, { symbol: "CMG", name: "Chipotle Mexican Grill, Inc." }, { symbol: "PH", name: "Parker-Hannifin Corporation" },
    { symbol: "JCI", name: "Johnson Controls International" }, { symbol: "ELV", name: "Elevance Health, Inc." }, { symbol: "ADSK", name: "Autodesk, Inc." },
    { symbol: "TTWO", name: "Take-Two Interactive Software," }, { symbol: "LMT", name: "Lockheed Martin Corporation" }, { symbol: "ADP", name: "Automatic Data Processing, Inc." },
    { symbol: "TT", name: "Trane Technologies plc" }, { symbol: "EQIX", name: "Equinix, Inc." }, { symbol: "BX", name: "Blackstone Inc." },
    { symbol: "DVN", name: "Devon Energy Corporation" }, { symbol: "LOW", name: "Lowe's Companies, Inc." }, { symbol: "DAL", name: "Delta Air Lines, Inc." },
    { symbol: "UAL", name: "United Airlines Holdings, Inc." }, { symbol: "SO", name: "Southern Company (The)" }, { symbol: "REGN", name: "Regeneron Pharmaceuticals, Inc." },
    { symbol: "HCA", name: "HCA Healthcare, Inc." }, { symbol: "TRV", name: "The Travelers Companies, Inc." }, { symbol: "MPC", name: "Marathon Petroleum Corporation" },
    { symbol: "AMT", name: "American Tower Corporation (REI" }, { symbol: "WBD", name: "Warner Bros. Discovery, Inc. -" }, { symbol: "MMM", name: "3M Company" },
    { symbol: "FSLR", name: "First Solar, Inc." }, { symbol: "CTSH", name: "Cognizant Technology Solutions" }, { symbol: "MAR", name: "Marriott International" },
    { symbol: "TGT", name: "Target Corporation" }, { symbol: "MO", name: "Altria Group, Inc." }, { symbol: "AON", name: "Aon plc" },
    { symbol: "JBL", name: "Jabil Inc." }, { symbol: "MDLZ", name: "Mondelez International, Inc." }, { symbol: "PLD", name: "Prologis, Inc." },
    { symbol: "URI", name: "United Rentals, Inc." }, { symbol: "BNY", name: "The Bank of New York Mellon Cor" }, { symbol: "DLR", name: "Digital Realty Trust, Inc." },
    { symbol: "MARA", name: "MARA Holdings, Inc." }, { symbol: "USB", name: "U.S. Bancorp" }, { symbol: "NOC", name: "Northrop Grumman Corporation" },
    { symbol: "UPS", name: "United Parcel Service, Inc." }, { symbol: "CSX", name: "CSX Corporation" }, { symbol: "CASY", name: "Caseys General Stores, Inc." },
    { symbol: "ZTS", name: "Zoetis Inc." }, { symbol: "VRSK", name: "Verisk Analytics, Inc." }, { symbol: "TFC", name: "Truist Financial Corporation" },
    { symbol: "SPG", name: "Simon Property Group, Inc." }, { symbol: "LULU", name: "lululemon athletica inc." }, { symbol: "PNC", name: "PNC Financial Services Group, I" },
    { symbol: "MNST", name: "Monster Beverage Corporation" }, { symbol: "WMB", name: "Williams Companies, Inc. (The)" }, { symbol: "CHTR", name: "Charter Communications, Inc." },
    { symbol: "KR", name: "Kroger Company (The)" }, { symbol: "EOG", name: "EOG Resources, Inc." }, { symbol: "CB", name: "Chubb Limited" },
    { symbol: "LNG", name: "Cheniere Energy, Inc." }, { symbol: "AXON", name: "Axon Enterprise, Inc." }, { symbol: "HUM", name: "Humana Inc." },
    { symbol: "WM", name: "Waste Management, Inc." }, { symbol: "AKAM", name: "Akamai Technologies, Inc." }, { symbol: "OXY", name: "Occidental Petroleum Corporatio" },
    { symbol: "TEL", name: "TE Connectivity plc" }, { symbol: "NTAP", name: "NetApp, Inc." }, { symbol: "CAH", name: "Cardinal Health, Inc." },
    { symbol: "FANG", name: "Diamondback Energy, Inc." }, { symbol: "KMB", name: "Kimberly-Clark Corporation" }, { symbol: "RIVN", name: "Rivian Automotive, Inc." },
    { symbol: "KDP", name: "Keurig Dr Pepper Inc." }, { symbol: "TDG", name: "Transdigm Group Incorporated" }, { symbol: "CRH", name: "CRH PLC" },
    { symbol: "CL", name: "Colgate-Palmolive Company" }, { symbol: "ECL", name: "Ecolab Inc." }, { symbol: "AEM", name: "Agnico Eagle Mines Limited" },
    { symbol: "XEL", name: "Xcel Energy Inc." }, { symbol: "B", name: "Barrick Mining Corporation" }, { symbol: "INSM", name: "Insmed Incorporated" },
    { symbol: "MCO", name: "Moody's Corporation" }, { symbol: "GD", name: "General Dynamics Corporation" }, { symbol: "HPQ", name: "HP Inc." },
    { symbol: "GWW", name: "W.W. Grainger, Inc." }, { symbol: "ODFL", name: "Old Dominion Freight Line, Inc." }, { symbol: "BKR", name: "Baker Hughes Company" },
    { symbol: "LYV", name: "Live Nation Entertainment, Inc." }, { symbol: "KKR", name: "KKR & Co. Inc." }, { symbol: "D", name: "Dominion Energy, Inc." },
    { symbol: "MSI", name: "Motorola Solutions, Inc." }, { symbol: "ULTA", name: "Ulta Beauty, Inc." }, { symbol: "FISV", name: "Fiserv, Inc." },
    { symbol: "HAL", name: "Halliburton Company" }, { symbol: "PSX", name: "Phillips 66" }, { symbol: "DUK", name: "Duke Energy Corporation (Holdin" },
    { symbol: "NUE", name: "Nucor Corporation" }, { symbol: "CI", name: "The Cigna Group" }, { symbol: "MRSH", name: "Marsh" },
    { symbol: "EW", name: "Edwards Lifesciences Corporatio" }, { symbol: "IBKR", name: "Interactive Brokers Group, Inc." }, { symbol: "TECH", name: "Bio-Techne Corp" },
    { symbol: "ROP", name: "Roper Technologies, Inc." }, { symbol: "TSCO", name: "Tractor Supply Company" }, { symbol: "LHX", name: "L3Harris Technologies, Inc." },
    { symbol: "TPR", name: "Tapestry, Inc." }, { symbol: "COR", name: "Cencora, Inc." }, { symbol: "BDX", name: "Becton, Dickinson and Company" },
    { symbol: "APD", name: "Air Products and Chemicals, Inc" }, { symbol: "RIOT", name: "Riot Platforms, Inc." }, { symbol: "MSCI", name: "MSCI Inc." },
    { symbol: "EA", name: "Electronic Arts Inc." }, { symbol: "ALL", name: "Allstate Corporation (The)" }, { symbol: "CCI", name: "Crown Castle Inc." },
    { symbol: "DLTR", name: "Dollar Tree, Inc." }, { symbol: "FITB", name: "Fifth Third Bancorp" }, { symbol: "STT", name: "State Street Corporation" },
    { symbol: "HSY", name: "The Hershey Company" }, { symbol: "AJG", name: "Arthur J. Gallagher & Co." }, { symbol: "DG", name: "Dollar General Corporation" },
    { symbol: "PPL", name: "PPL Corporation" }, { symbol: "ENPH", name: "Enphase Energy, Inc." }, { symbol: "PCAR", name: "PACCAR Inc." },
    { symbol: "EMR", name: "Emerson Electric Company" }, { symbol: "SRE", name: "DBA Sempra" }, { symbol: "EXC", name: "Exelon Corporation" },
    { symbol: "EBAY", name: "eBay Inc." }, { symbol: "SWKS", name: "Skyworks Solutions, Inc." }, { symbol: "O", name: "Realty Income Corporation" },
    { symbol: "ALB", name: "Albemarle Corporation" }, { symbol: "ROK", name: "Rockwell Automation, Inc." }, { symbol: "EXPE", name: "Expedia Group, Inc." },
    { symbol: "KVUE", name: "Kenvue Inc." }, { symbol: "EQT", name: "EQT Corporation" }, { symbol: "ETR", name: "Entergy Corporation" },
    { symbol: "NDAQ", name: "Nasdaq, Inc." }, { symbol: "CPRT", name: "Copart, Inc." }, { symbol: "HBAN", name: "Huntington Bancshares Incorpora" },
    { symbol: "CTAS", name: "Cintas Corporation" }, { symbol: "VMC", name: "Vulcan Materials Company (Holdi" }, { symbol: "DXCM", name: "DexCom, Inc." },
    { symbol: "ITW", name: "Illinois Tool Works Inc." }, { symbol: "FICO", name: "Fair Isaac Corporation" }, { symbol: "EME", name: "EMCOR Group, Inc." },
    { symbol: "NRG", name: "NRG Energy, Inc." }, { symbol: "IDXX", name: "IDEXX Laboratories, Inc." }, { symbol: "AA", name: "Alcoa Corporation" },
    { symbol: "PAYX", name: "Paychex, Inc." }, { symbol: "OMC", name: "Omnicom Group Inc." }, { symbol: "WAT", name: "Waters Corporation" },
    { symbol: "GIS", name: "General Mills, Inc." }, { symbol: "MLM", name: "Martin Marietta Materials, Inc." }, { symbol: "CNC", name: "Centene Corporation" },
    { symbol: "VALE", name: "VALE S.A." }, { symbol: "RSG", name: "Republic Services, Inc." }, { symbol: "YUM", name: "Yum! Brands, Inc." },
    { symbol: "CCJ", name: "Cameco Corporation" }, { symbol: "DKNG", name: "DraftKings Inc." }, { symbol: "AU", name: "AngloGold Ashanti PLC" },
    { symbol: "VTR", name: "Ventas, Inc." }, { symbol: "ILMN", name: "Illumina, Inc." }, { symbol: "AMP", name: "Ameriprise Financial, Inc." },
    { symbol: "AIG", name: "American International Group, I" }, { symbol: "NSC", name: "Norfolk Southern Corporation" }, { symbol: "DHI", name: "D.R. Horton, Inc." },
  ],
  "Setores": [
    { symbol: "XLK", name: "Technology" }, { symbol: "XLV", name: "Healthcare" }, { symbol: "XLF", name: "Financials" },
    { symbol: "XLY", name: "Consumer Discretionary" }, { symbol: "XLP", name: "Consumer Staples" }, { symbol: "XLC", name: "Communication Services" },
    { symbol: "XLI", name: "Industrials" }, { symbol: "XLE", name: "Energy" }, { symbol: "XLU", name: "Utilities" },
    { symbol: "XLB", name: "Materials" }, { symbol: "XLRE", name: "Real Estate" },
  ],
  "Commodities": [
    { symbol: "GC=F", name: "Gold" }, { symbol: "SI=F", name: "Silver" }, { symbol: "PL=F", name: "Platinum" },
    { symbol: "PA=F", name: "Palladium" }, { symbol: "HG=F", name: "Copper" }, { symbol: "CL=F", name: "WTI Crude Oil" },
    { symbol: "BZ=F", name: "Brent Crude Oil" }, { symbol: "NG=F", name: "Natural Gas" }, { symbol: "RB=F", name: "Gasoline" },
    { symbol: "HO=F", name: "Heating Oil" }, { symbol: "ZC=F", name: "Corn" }, { symbol: "ZW=F", name: "Wheat" },
    { symbol: "ZS=F", name: "Soybeans" }, { symbol: "KC=F", name: "Coffee" }, { symbol: "SB=F", name: "Sugar" },
    { symbol: "CC=F", name: "Cocoa" }, { symbol: "CT=F", name: "Cotton" }, { symbol: "LE=F", name: "Live Cattle" },
  ],
  "Cripto": [
    { symbol: "BTC-USD", name: "Bitcoin" }, { symbol: "ETH-USD", name: "Ethereum" }, { symbol: "SOL-USD", name: "Solana" },
    { symbol: "XRP-USD", name: "XRP" }, { symbol: "BNB-USD", name: "BNB" }, { symbol: "ADA-USD", name: "Cardano" },
    { symbol: "DOGE-USD", name: "Dogecoin" }, { symbol: "AVAX-USD", name: "Avalanche" }, { symbol: "LINK-USD", name: "Chainlink" },
    { symbol: "DOT-USD", name: "Polkadot" }, { symbol: "MATIC-USD", name: "Polygon" }, { symbol: "LTC-USD", name: "Litecoin" },
    { symbol: "BCH-USD", name: "Bitcoin Cash" }, { symbol: "TRX-USD", name: "TRON" }, { symbol: "UNI-USD", name: "Uniswap" },
    { symbol: "SHIB-USD", name: "Shiba Inu" },
  ],
  "Forex": [
    { symbol: "USDBRL=X", name: "USD / BRL (dollar-real)" }, { symbol: "EURUSD=X", name: "EUR / USD" },
    { symbol: "USDJPY=X", name: "USD / JPY" }, { symbol: "GBPUSD=X", name: "GBP / USD" },
    { symbol: "USDCHF=X", name: "USD / CHF" }, { symbol: "AUDUSD=X", name: "AUD / USD" },
    { symbol: "USDCAD=X", name: "USD / CAD" }, { symbol: "NZDUSD=X", name: "NZD / USD" },
    { symbol: "USDMXN=X", name: "USD / MXN" }, { symbol: "USDCNY=X", name: "USD / CNY" },
    { symbol: "USDARS=X", name: "USD / ARS" }, { symbol: "EURBRL=X", name: "EUR / BRL" },
    { symbol: "EURGBP=X", name: "EUR / GBP" }, { symbol: "EURJPY=X", name: "EUR / JPY" },
    { symbol: "USDZAR=X", name: "USD / ZAR" }, { symbol: "USDTRY=X", name: "USD / TRY" },
  ],
};

// Selector for the "Stocks, ETFs & Commodities" screen — grouped (optgroup)
export const ASSET_GROUPS: { label: string; items: SymbolDef[] }[] = [
  { label: "Stocks", items: MARKET_GROUPS["Ações"] },
  { label: "US Indices", items: MARKET_GROUPS["Índices US"] },
  { label: "Global Indices", items: MARKET_GROUPS["Índices Globais"] },
  { label: "ETFs", items: MARKET_GROUPS["ETFs"] },
  { label: "Sectors", items: MARKET_GROUPS["Setores"] },
  { label: "Commodities", items: MARKET_GROUPS["Commodities"] },
  { label: "Crypto", items: MARKET_GROUPS["Cripto"] },
  { label: "Forex", items: MARKET_GROUPS["Forex"] },
];
export const ASSET_LIST: SymbolDef[] = ASSET_GROUPS.flatMap((g) => g.items);

// Yahoo → TradingView symbol map (for the widget/deep-link).
const TV_MAP: Record<string, string> = {
  "^GSPC": "SP:SPX", "^NDX": "NASDAQ:NDX", "^DJI": "DJ:DJI", "^RUT": "TVC:RUT2K", "^SOX": "NASDAQ:SOX", "^VIX": "TVC:VIX",
  "GC=F": "COMEX:GC1!", "SI=F": "COMEX:SI1!", "CL=F": "NYMEX:CL1!", "BZ=F": "NYMEX:BZ1!", "NG=F": "NYMEX:NG1!", "HG=F": "COMEX:HG1!",
  "BTC-USD": "COINBASE:BTCUSD", "ETH-USD": "COINBASE:ETHUSD", "SOL-USD": "COINBASE:SOLUSD", "XRP-USD": "COINBASE:XRPUSD", "BNB-USD": "BINANCE:BNBUSD", "DOGE-USD": "COINBASE:DOGEUSD",
  "EURUSD=X": "FX:EURUSD", "USDJPY=X": "FX:USDJPY", "GBPUSD=X": "FX:GBPUSD", "USDBRL=X": "FX_IDC:USDBRL", "USDCHF=X": "FX:USDCHF", "AUDUSD=X": "FX:AUDUSD",
};
export const tvSymbol = (s: string) => TV_MAP[s] || s.replace("^", "").replace("=F", "").replace("-USD", "USD").replace("=X", "");


// Sample client portfolio (aggressive) — portfolio Risk comes from here, live from Yahoo.
export const EXAMPLE_PORTFOLIO: { symbol: string; weight: number }[] = [
  { symbol: "QQQ", weight: 0.30 },
  { symbol: "NVDA", weight: 0.25 },
  { symbol: "TSLA", weight: 0.20 },
  { symbol: "META", weight: 0.15 },
  { symbol: "AMZN", weight: 0.10 },
];
