// Portfólios modelo Harpian (P1-P6) — dado real, transcrito das planilhas
// institucionais "Portfólios modelos para HIS" (Risk Number MFO). Cada item é uma
// linha real do Excel: Produto/Emissor/Categoria/Sub-Categoria/Geografia/Ticker/
// Alocação%/Perfil de Risco (+ Retorno/Volatilidade/Fonte quando a planilha traz).
// Usado como TEMPLATE reutilizável nos portfólios dos clientes-exemplo do Terminal
// — a mesma planilha pode ser aplicada a vários clientes (é um modelo de referência).
export interface PortfolioItemDetail {
  produto: string;
  emissor: string;
  categoria: string;
  subCategoria: string;
  geografia: string;         // ou "Setor/Foco" nos modelos 100% EUA
  ticker: string;
  alocacaoPct: number;       // 0–1
  valorUsd: number;          // sobre a base do modelo (USD 100.000)
  perfilRisco: string;
  retornoNativoPct?: number;
  retornoUsdPct?: number;
  volatilidadePct?: number;
  fonte?: string;
}

export const MODEL_P1: PortfolioItemDetail[] = [
  { produto: "NTN-B 2029", emissor: "Tesouro Nacional", categoria: "Título Soberano", subCategoria: "Tesouro IPCA+", geografia: "Brasil", ticker: "NTNB29", alocacaoPct: 0.15, valorUsd: 15000, perfilRisco: "Muito Baixo" },
  { produto: "LFT 2026", emissor: "Tesouro Nacional", categoria: "Título Soberano", subCategoria: "Tesouro Selic", geografia: "Brasil", ticker: "LFT26", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Muito Baixo" },
  { produto: "CDB BTG 120% CDI", emissor: "BTG Pactual", categoria: "Renda Fixa", subCategoria: "CDB Pós-Fixado", geografia: "Brasil", ticker: "CDB-BTG", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Baixo" },
  { produto: "LCI Itaú 2026", emissor: "Itaú BBA", categoria: "Renda Fixa", subCategoria: "LCI Pós-Fixada", geografia: "Brasil", ticker: "LCI-ITA", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Baixo" },
  { produto: "XP Crédito Privado FIC FI RF", emissor: "XP Asset Management", categoria: "Fundo RF", subCategoria: "Crédito Privado", geografia: "Brasil", ticker: "XPCP11", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo-Médio" },
  { produto: "BTG Infra Debêntures FIC FIM", emissor: "BTG Pactual Asset Mgmt", categoria: "Fundo RF", subCategoria: "Debêntures Incentivadas", geografia: "Brasil", ticker: "BTGI11", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo-Médio" },
  { produto: "Verde Asset FIC FIM", emissor: "Verde Asset Management", categoria: "Fundo Multimercado", subCategoria: "Long/Short Macro", geografia: "Brasil", ticker: "VERDE", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Médio-Baixo" },
  { produto: "BOVA11", emissor: "BlackRock Brasil", categoria: "Renda Variável", subCategoria: "ETF Ações BR", geografia: "Brasil", ticker: "BOVA11.SA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "Bond ETF EUA", geografia: "EUA", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo" },
  { produto: "TLT — iShares 20+ Year Treasury", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "Treasury ETF", geografia: "EUA", ticker: "TLT", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Baixo-Médio" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Renda Variável", subCategoria: "ETF Large-Cap EUA", geografia: "EUA", ticker: "SPY", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio" },
];

export const MODEL_P2: PortfolioItemDetail[] = [
  { produto: "NTN-B 2029", emissor: "Tesouro Nacional", categoria: "Título Soberano", subCategoria: "Tesouro IPCA+", geografia: "Brasil", ticker: "NTNB29", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Muito Baixo", retornoNativoPct: 0.115, retornoUsdPct: 0.025, volatilidadePct: 0.04, fonte: "Tesouro IPCA+ histórico; depreciação BRL ~8,5%/ano" },
  { produto: "CDB BTG 120% CDI", emissor: "BTG Pactual", categoria: "Renda Fixa", subCategoria: "CDB Pós-Fixado", geografia: "Brasil", ticker: "CDB-BTG", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Baixo", retornoNativoPct: 0.126, retornoUsdPct: 0.032, volatilidadePct: 0.02, fonte: "120% CDI ~12,6% BRL; ajustado FX" },
  { produto: "LCI Itaú 2026", emissor: "Itaú BBA", categoria: "Renda Fixa", subCategoria: "LCI Pós-Fixada", geografia: "Brasil", ticker: "LCI-ITA", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo", retornoNativoPct: 0.095, retornoUsdPct: 0.008, volatilidadePct: 0.01, fonte: "90% CDI isento IR; ajustado FX" },
  { produto: "BTG Infra Debêntures FIC FIM", emissor: "BTG Pactual Asset Mgmt", categoria: "Fundo RF", subCategoria: "Debêntures Incentivadas", geografia: "Brasil", ticker: "BTGI11", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Baixo-Médio", retornoNativoPct: 0.135, retornoUsdPct: 0.04, volatilidadePct: 0.04, fonte: "Debêntures incentivadas IPCA+6%; ajustado FX" },
  { produto: "Verde Asset FIC FIM", emissor: "Verde Asset Management", categoria: "Fundo Multimercado", subCategoria: "Long/Short Macro", geografia: "Brasil", ticker: "VERDE", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Médio-Baixo", retornoNativoPct: 0.16, retornoUsdPct: 0.064, volatilidadePct: 0.08, fonte: "Verde Asset CAGR 10a BRL; ajustado FX" },
  { produto: "Alaska Black FIC FIA", emissor: "Alaska Asset Management", categoria: "Fundo Ações BR", subCategoria: "Long Only Value", geografia: "Brasil", ticker: "ALASKA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.20, retornoUsdPct: 0.10, volatilidadePct: 0.20, fonte: "Alaska Black média histórica 10a BRL" },
  { produto: "BOVA11", emissor: "BlackRock Brasil", categoria: "Renda Variável", subCategoria: "ETF Ações BR", geografia: "Brasil", ticker: "BOVA11.SA", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Médio", retornoNativoPct: 0.10, retornoUsdPct: 0.008, volatilidadePct: 0.22, fonte: "Ibovespa média 10a BRL; ajustado FX" },
  { produto: "KNRI11 — Kinea Renda Imobiliária", emissor: "Kinea Investimentos", categoria: "Renda Variável", subCategoria: "FII Tijolo", geografia: "Brasil", ticker: "KNRI11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.11, retornoUsdPct: 0.018, volatilidadePct: 0.15, fonte: "FII Kinea dividendos + valorização BRL" },
  { produto: "IVVB11 — iShares S&P 500", emissor: "BlackRock Brasil", categoria: "Renda Variável", subCategoria: "ETF S&P500 BR", geografia: "Brasil", ticker: "IVVB11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.24, retornoUsdPct: 0.133, volatilidadePct: 0.18, fonte: "SPY em BRL (retorno USD + depreciação BRL)" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "Bond ETF EUA", geografia: "EUA", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond média 10a (2015-2025); Bloomberg" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Renda Variável", subCategoria: "ETF Large-Cap EUA", geografia: "EUA", ticker: "SPY", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 média 10a (2015-2025); Bloomberg" },
  { produto: "QUAL — iShares MSCI USA Quality", emissor: "BlackRock", categoria: "Renda Variável", subCategoria: "ETF Quality Factor", geografia: "EUA", ticker: "QUAL", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.138, retornoUsdPct: 0.138, volatilidadePct: 0.17, fonte: "MSCI Quality Factor média 10a; BlackRock" },
  { produto: "IEV — iShares MSCI Europe ETF", emissor: "BlackRock", categoria: "Renda Variável", subCategoria: "ETF Ações Europa", geografia: "Europa", ticker: "IEV", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.075, retornoUsdPct: 0.075, volatilidadePct: 0.18, fonte: "MSCI Europe ETF USD média 10a" },
  { produto: "IBGX — iShares € Govt Bond UCITS ETF", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "Soberano EUR", geografia: "Europa", ticker: "IBGX", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Baixo", retornoNativoPct: 0.015, retornoUsdPct: 0.015, volatilidadePct: 0.06, fonte: "EUR Govt Bond UCITS USD média 10a" },
];

export const MODEL_P3: PortfolioItemDetail[] = [
  { produto: "U.S. Treasury Note 2Y", emissor: "U.S. Department of Treasury", categoria: "Título Soberano", subCategoria: "T-Note 2 anos", geografia: "EUA", ticker: "USTNT2Y", alocacaoPct: 0.15, valorUsd: 15000, perfilRisco: "Muito Baixo", retornoNativoPct: 0.047, retornoUsdPct: 0.047, volatilidadePct: 0.03, fonte: "US T-Note 2Y yield atual jun/2026" },
  { produto: "U.S. Treasury Bond 10Y", emissor: "U.S. Department of Treasury", categoria: "Título Soberano", subCategoria: "T-Bond 10 anos", geografia: "EUA", ticker: "USTNB10", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Muito Baixo", retornoNativoPct: 0.044, retornoUsdPct: 0.044, volatilidadePct: 0.08, fonte: "US T-Bond 10Y yield atual jun/2026" },
  { produto: "TLT — iShares 20+ Year Treasury", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "Treasury ETF L-G", geografia: "EUA", ticker: "TLT", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Baixo-Médio", retornoNativoPct: 0.02, retornoUsdPct: 0.02, volatilidadePct: 0.14, fonte: "iShares 20+ yr; retorno 10a deprimido por alta juros" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "Bond ETF Broad", geografia: "EUA", ticker: "AGG", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Baixo", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond média 10a (2015-2025); Bloomberg" },
  { produto: "BND — Vanguard Total Bond Market ETF", emissor: "Vanguard", categoria: "ETF Renda Fixa", subCategoria: "Bond ETF Total", geografia: "EUA", ticker: "BND", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "Vanguard Total Bond média 10a" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Renda Variável", subCategoria: "ETF Large-Cap", geografia: "EUA", ticker: "SPY", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Médio", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 média 10a (2015-2025); Bloomberg" },
  { produto: "IVV — iShares Core S&P 500 ETF", emissor: "BlackRock", categoria: "Renda Variável", subCategoria: "ETF S&P500", geografia: "EUA", ticker: "IVV", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Médio", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "iShares S&P 500 média 10a" },
  { produto: "VIG — Vanguard Dividend Appreciation ETF", emissor: "Vanguard", categoria: "Renda Variável", subCategoria: "ETF Dividendos", geografia: "EUA", ticker: "VIG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Médio", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Dividend Appreciation média 10a; Vanguard" },
  { produto: "QUAL — iShares MSCI USA Quality Factor", emissor: "BlackRock", categoria: "Renda Variável", subCategoria: "ETF Quality Factor", geografia: "EUA", ticker: "QUAL", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.138, retornoUsdPct: 0.138, volatilidadePct: 0.17, fonte: "MSCI Quality Factor média 10a; BlackRock" },
  { produto: "IYR — iShares US Real Estate ETF", emissor: "BlackRock", categoria: "Renda Variável", subCategoria: "ETF REITs EUA", geografia: "EUA", ticker: "IYR", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.085, retornoUsdPct: 0.085, volatilidadePct: 0.20, fonte: "US REITs média 10a; NAREIT" },
  { produto: "QQQ — Invesco NASDAQ 100 ETF", emissor: "Invesco", categoria: "Renda Variável", subCategoria: "ETF Nasdaq 100", geografia: "EUA", ticker: "QQQ", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.18, retornoUsdPct: 0.18, volatilidadePct: 0.22, fonte: "NASDAQ 100 média 10a (2015-2025)" },
];

export const MODEL_P4: PortfolioItemDetail[] = [
  { produto: "NTN-B 2029", emissor: "Tesouro Nacional", categoria: "Título Soberano", subCategoria: "Tesouro IPCA+", geografia: "Brasil", ticker: "NTNB29", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Muito Baixo", retornoNativoPct: 0.115, retornoUsdPct: 0.025, volatilidadePct: 0.04, fonte: "Tesouro IPCA+ histórico; depreciação BRL ~8,5%/ano" },
  { produto: "CDB BTG 120% CDI", emissor: "BTG Pactual", categoria: "Renda Fixa", subCategoria: "CDB Pós-Fixado", geografia: "Brasil", ticker: "CDB-BTG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo", retornoNativoPct: 0.126, retornoUsdPct: 0.032, volatilidadePct: 0.02, fonte: "120% CDI ~12,6% BRL; ajustado FX" },
  { produto: "LCI Itaú 2026", emissor: "Itaú BBA", categoria: "Renda Fixa", subCategoria: "LCI Pós-Fixada", geografia: "Brasil", ticker: "LCI-ITA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Baixo", retornoNativoPct: 0.095, retornoUsdPct: 0.008, volatilidadePct: 0.01, fonte: "90% CDI isento IR; ajustado FX" },
  { produto: "Verde Asset FIC FIM", emissor: "Verde Asset Management", categoria: "Fundo Multimercado", subCategoria: "Long/Short Macro", geografia: "Brasil", ticker: "VERDE", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Médio-Baixo", retornoNativoPct: 0.16, retornoUsdPct: 0.064, volatilidadePct: 0.08, fonte: "Verde Asset CAGR 10a BRL; ajustado FX" },
  { produto: "BOVA11", emissor: "BlackRock Brasil", categoria: "Renda Variável", subCategoria: "ETF Ações BR", geografia: "Brasil", ticker: "BOVA11.SA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio", retornoNativoPct: 0.10, retornoUsdPct: 0.008, volatilidadePct: 0.22, fonte: "Ibovespa média 10a BRL; ajustado FX" },
  { produto: "HASH11 — Hashdex Crypto Index", emissor: "Hashdex", categoria: "Renda Variável", subCategoria: "ETF Crypto", geografia: "Brasil", ticker: "HASH11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Alto", retornoNativoPct: 0.45, retornoUsdPct: 0.32, volatilidadePct: 0.70, fonte: "Hashdex Crypto Index; alta volatilidade" },
  { produto: "KNRI11 — Kinea Renda Imobiliária", emissor: "Kinea Investimentos", categoria: "Renda Variável", subCategoria: "FII Tijolo", geografia: "Brasil", ticker: "KNRI11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.11, retornoUsdPct: 0.018, volatilidadePct: 0.15, fonte: "FII Kinea dividendos + valorização BRL" },
  { produto: "U.S. Treasury Bond 10Y", emissor: "U.S. Department of Treasury", categoria: "Título Soberano", subCategoria: "T-Bond 10 anos", geografia: "EUA", ticker: "USTNB10", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Muito Baixo", retornoNativoPct: 0.044, retornoUsdPct: 0.044, volatilidadePct: 0.08, fonte: "US T-Bond 10Y yield atual jun/2026" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "Bond ETF Broad", geografia: "EUA", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond média 10a (2015-2025); Bloomberg" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Renda Variável", subCategoria: "ETF Large-Cap", geografia: "EUA", ticker: "SPY", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Médio", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 média 10a (2015-2025); Bloomberg" },
  { produto: "IVV — iShares Core S&P 500 ETF", emissor: "BlackRock", categoria: "Renda Variável", subCategoria: "ETF S&P500", geografia: "EUA", ticker: "IVV", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "iShares S&P 500 média 10a" },
  { produto: "VIG — Vanguard Dividend Appreciation ETF", emissor: "Vanguard", categoria: "Renda Variável", subCategoria: "ETF Dividendos", geografia: "EUA", ticker: "VIG", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Dividend Appreciation média 10a; Vanguard" },
  { produto: "IEV — iShares MSCI Europe ETF", emissor: "BlackRock", categoria: "Renda Variável", subCategoria: "ETF Ações Europa", geografia: "Europa", ticker: "IEV", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.075, retornoUsdPct: 0.075, volatilidadePct: 0.18, fonte: "MSCI Europe ETF USD média 10a" },
  { produto: "Petrobras USD Bond 2030", emissor: "Petróleo Brasileiro S.A.", categoria: "Eurobond", subCategoria: "Corp Bond USD", geografia: "Brasil", ticker: "PBR2030", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Baixo-Médio", retornoNativoPct: 0.065, retornoUsdPct: 0.065, volatilidadePct: 0.12, fonte: "Petrobras USD Bond 2030 yield to maturity" },
];

export const MODEL_P5: PortfolioItemDetail[] = [
  { produto: "U.S. Treasury Note 2Y", emissor: "U.S. Treasury", categoria: "Título Soberano", subCategoria: "Título Soberano", geografia: "Soberano Curto Prazo", ticker: "USTNT2Y", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Muito Baixo", retornoNativoPct: 0.047, retornoUsdPct: 0.047, volatilidadePct: 0.03, fonte: "US T-Note 2Y yield atual jun/2026" },
  { produto: "U.S. Treasury Bond 10Y", emissor: "U.S. Treasury", categoria: "Título Soberano", subCategoria: "Título Soberano", geografia: "Soberano Longo Prazo", ticker: "USTNB10", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Muito Baixo", retornoNativoPct: 0.044, retornoUsdPct: 0.044, volatilidadePct: 0.08, fonte: "US T-Bond 10Y yield atual jun/2026" },
  { produto: "AGG — iShares Core US Aggregate", emissor: "BlackRock", categoria: "ETF Renda Fixa", subCategoria: "ETF Renda Fixa", geografia: "Bond Broad Market", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Baixo", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond média 10a (2015-2025); Bloomberg" },
  { produto: "Apple Inc.", emissor: "Apple Inc.", categoria: "Renda Variável", subCategoria: "Ação Individual", geografia: "Technology — Consumer", ticker: "AAPL", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.25, retornoUsdPct: 0.25, volatilidadePct: 0.25, fonte: "Apple Inc média 10a" },
  { produto: "Microsoft Corp.", emissor: "Microsoft Corp.", categoria: "Renda Variável", subCategoria: "Ação Individual", geografia: "Technology — Enterprise", ticker: "MSFT", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.275, retornoUsdPct: 0.275, volatilidadePct: 0.23, fonte: "Microsoft Corp média 10a" },
  { produto: "Alphabet Inc. Cl-A", emissor: "Alphabet Inc.", categoria: "Renda Variável", subCategoria: "Ação Individual", geografia: "Technology — Ads/Cloud", ticker: "GOOGL", alocacaoPct: 0.06, valorUsd: 6000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.18, retornoUsdPct: 0.18, volatilidadePct: 0.25, fonte: "Alphabet Inc média 10a" },
  { produto: "JPMorgan Chase & Co.", emissor: "JPMorgan Chase", categoria: "Renda Variável", subCategoria: "Ação Individual", geografia: "Financials — Banking", ticker: "JPM", alocacaoPct: 0.06, valorUsd: 6000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.15, retornoUsdPct: 0.15, volatilidadePct: 0.22, fonte: "JPMorgan Chase média 10a" },
  { produto: "Johnson & Johnson", emissor: "J&J", categoria: "Renda Variável", subCategoria: "Ação Individual", geografia: "Healthcare — Diversified", ticker: "JNJ", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.08, retornoUsdPct: 0.08, volatilidadePct: 0.14, fonte: "Johnson & Johnson média 10a" },
  { produto: "Berkshire Hathaway Cl-B", emissor: "Berkshire Hathaway", categoria: "Renda Variável", subCategoria: "Ação Individual", geografia: "Financials — Conglomerate", ticker: "BRK-B", alocacaoPct: 0.04, valorUsd: 4000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.13, retornoUsdPct: 0.13, volatilidadePct: 0.18, fonte: "Berkshire Hathaway Cl-B média 10a" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Renda Variável", subCategoria: "ETF Renda Variável", geografia: "S&P 500 Broad Market", ticker: "SPY", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Médio", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 média 10a (2015-2025); Bloomberg" },
  { produto: "QQQ — Invesco NASDAQ-100 ETF", emissor: "Invesco", categoria: "Renda Variável", subCategoria: "ETF Renda Variável", geografia: "Tech / Growth NASDAQ", ticker: "QQQ", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Médio-Alto", retornoNativoPct: 0.18, retornoUsdPct: 0.18, volatilidadePct: 0.22, fonte: "NASDAQ 100 média 10a (2015-2025)" },
  { produto: "VIG — Vanguard Dividend Appreciation", emissor: "Vanguard", categoria: "Renda Variável", subCategoria: "ETF Renda Variável", geografia: "Dividend Growth", ticker: "VIG", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Médio", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Dividend Appreciation média 10a; Vanguard" },
  { produto: "VYM — Vanguard High Dividend Yield", emissor: "Vanguard", categoria: "Renda Variável", subCategoria: "ETF Renda Variável", geografia: "High Yield Dividend", ticker: "VYM", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.10, retornoUsdPct: 0.10, volatilidadePct: 0.16, fonte: "High Dividend Yield média 10a; Vanguard" },
  { produto: "VHT — Vanguard Health Care ETF", emissor: "Vanguard", categoria: "Renda Variável", subCategoria: "ETF Renda Variável", geografia: "Healthcare Sector", ticker: "VHT", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Médio", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Healthcare ETF média 10a; Vanguard" },
  { produto: "IBIT — iShares Bitcoin Trust ETF", emissor: "BlackRock", categoria: "ETF Crypto", subCategoria: "ETF Crypto", geografia: "Bitcoin — ETF Regulado", ticker: "IBIT", alocacaoPct: 0.02, valorUsd: 2000, perfilRisco: "Alto", retornoNativoPct: 0.30, retornoUsdPct: 0.30, volatilidadePct: 0.70, fonte: "Bitcoin ETF; histórico BTC 10a; alta volatilidade" },
];

export const MODEL_P6: PortfolioItemDetail[] = [
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street Global Advisors", categoria: "Renda Variável", subCategoria: "ETF", geografia: "S&P 500 — 500 maiores empresas EUA", ticker: "SPY", alocacaoPct: 1, valorUsd: 100000, perfilRisco: "Médio" },
];

export const MODELS: Record<string, { label: string; subtitle: string; items: PortfolioItemDetail[] }> = {
  P1: { label: "P1 — Conservador Brasil", subtitle: "80% Brasil | 20% EUA · Perfil Conservador", items: MODEL_P1 },
  P2: { label: "P2 — Conservador-Moderado Global", subtitle: "70% Brasil | 20% EUA | 10% Europa", items: MODEL_P2 },
  P3: { label: "P3 — Conservador EUA", subtitle: "100% EUA · USD Puro", items: MODEL_P3 },
  P4: { label: "P4 — Balanceado Moderado Global", subtitle: "50% Brasil | 40% EUA | 10% Europa", items: MODEL_P4 },
  P5: { label: "P5 — Moderado EUA", subtitle: "100% USD · ações diretas + ETFs + treasuries", items: MODEL_P5 },
  P6: { label: "P6 — Agressivo EUA", subtitle: "100% S&P 500 (SPY) · benchmark", items: MODEL_P6 },
};
