// Harpian model portfolios (P1-P6) — real data, transcribed from the
// institutional "Portfólios modelos para HIS" spreadsheets (Risk Number MFO). Each item
// is a real row from the Excel: Product/Issuer/Category/Sub-Category/Geography/Ticker/
// Allocation%/Risk Profile (+ Return/Volatility/Source when the spreadsheet provides them).
// Used as a reusable TEMPLATE across the Terminal's example-client portfolios
// — the same spreadsheet can be applied to several clients (it's a reference model).
export interface PortfolioItemDetail {
  produto: string;
  emissor: string;
  categoria: string;
  subCategoria: string;
  geografia: string;         // or "Sector/Focus" in the 100% US models
  ticker: string;
  alocacaoPct: number;       // 0–1
  valorUsd: number;          // on the model's base (USD 100,000)
  perfilRisco: string;
  retornoNativoPct?: number;
  retornoUsdPct?: number;
  volatilidadePct?: number;
  fonte?: string;
}

export const MODEL_P1: PortfolioItemDetail[] = [
  { produto: "NTN-B 2029", emissor: "Brazilian National Treasury", categoria: "Sovereign Bond", subCategoria: "Tesouro IPCA+", geografia: "Brazil", ticker: "NTNB29", alocacaoPct: 0.15, valorUsd: 15000, perfilRisco: "Very Low" },
  { produto: "LFT 2026", emissor: "Brazilian National Treasury", categoria: "Sovereign Bond", subCategoria: "Tesouro Selic", geografia: "Brazil", ticker: "LFT26", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Very Low" },
  { produto: "CDB BTG 120% CDI", emissor: "BTG Pactual", categoria: "Fixed Income", subCategoria: "Floating-Rate CDB", geografia: "Brazil", ticker: "CDB-BTG", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Low" },
  { produto: "LCI Itaú 2026", emissor: "Itaú BBA", categoria: "Fixed Income", subCategoria: "Floating-Rate LCI", geografia: "Brazil", ticker: "LCI-ITA", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Low" },
  { produto: "XP Crédito Privado FIC FI RF", emissor: "XP Asset Management", categoria: "Fixed Income Fund", subCategoria: "Private Credit", geografia: "Brazil", ticker: "XPCP11", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low-Medium" },
  { produto: "BTG Infra Debêntures FIC FIM", emissor: "BTG Pactual Asset Mgmt", categoria: "Fixed Income Fund", subCategoria: "Tax-Incentivized Debentures", geografia: "Brazil", ticker: "BTGI11", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low-Medium" },
  { produto: "Verde Asset FIC FIM", emissor: "Verde Asset Management", categoria: "Multi-Strategy Fund", subCategoria: "Long/Short Macro", geografia: "Brazil", ticker: "VERDE", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Medium-Low" },
  { produto: "BOVA11", emissor: "BlackRock Brasil", categoria: "Equities", subCategoria: "Brazil Equity ETF", geografia: "Brazil", ticker: "BOVA11.SA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "US Bond ETF", geografia: "USA", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low" },
  { produto: "TLT — iShares 20+ Year Treasury", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "Treasury ETF", geografia: "USA", ticker: "TLT", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Low-Medium" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Equities", subCategoria: "US Large-Cap ETF", geografia: "USA", ticker: "SPY", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium" },
];

export const MODEL_P2: PortfolioItemDetail[] = [
  { produto: "NTN-B 2029", emissor: "Brazilian National Treasury", categoria: "Sovereign Bond", subCategoria: "Tesouro IPCA+", geografia: "Brazil", ticker: "NTNB29", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Very Low", retornoNativoPct: 0.115, retornoUsdPct: 0.025, volatilidadePct: 0.04, fonte: "Historical Tesouro IPCA+; BRL depreciation ~8.5%/yr" },
  { produto: "CDB BTG 120% CDI", emissor: "BTG Pactual", categoria: "Fixed Income", subCategoria: "Floating-Rate CDB", geografia: "Brazil", ticker: "CDB-BTG", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Low", retornoNativoPct: 0.126, retornoUsdPct: 0.032, volatilidadePct: 0.02, fonte: "120% CDI ~12.6% BRL; FX-adjusted" },
  { produto: "LCI Itaú 2026", emissor: "Itaú BBA", categoria: "Fixed Income", subCategoria: "Floating-Rate LCI", geografia: "Brazil", ticker: "LCI-ITA", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low", retornoNativoPct: 0.095, retornoUsdPct: 0.008, volatilidadePct: 0.01, fonte: "90% CDI, tax-exempt; FX-adjusted" },
  { produto: "BTG Infra Debêntures FIC FIM", emissor: "BTG Pactual Asset Mgmt", categoria: "Fixed Income Fund", subCategoria: "Tax-Incentivized Debentures", geografia: "Brazil", ticker: "BTGI11", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Low-Medium", retornoNativoPct: 0.135, retornoUsdPct: 0.04, volatilidadePct: 0.04, fonte: "Tax-incentivized debentures IPCA+6%; FX-adjusted" },
  { produto: "Verde Asset FIC FIM", emissor: "Verde Asset Management", categoria: "Multi-Strategy Fund", subCategoria: "Long/Short Macro", geografia: "Brazil", ticker: "VERDE", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Medium-Low", retornoNativoPct: 0.16, retornoUsdPct: 0.064, volatilidadePct: 0.08, fonte: "Verde Asset 10-year CAGR, BRL; FX-adjusted" },
  { produto: "Alaska Black FIC FIA", emissor: "Alaska Asset Management", categoria: "Brazilian Equity Fund", subCategoria: "Long Only Value", geografia: "Brazil", ticker: "ALASKA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium-High", retornoNativoPct: 0.20, retornoUsdPct: 0.10, volatilidadePct: 0.20, fonte: "Alaska Black 10-year historical average, BRL" },
  { produto: "BOVA11", emissor: "BlackRock Brasil", categoria: "Equities", subCategoria: "Brazil Equity ETF", geografia: "Brazil", ticker: "BOVA11.SA", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Medium", retornoNativoPct: 0.10, retornoUsdPct: 0.008, volatilidadePct: 0.22, fonte: "Ibovespa 10-year average, BRL; FX-adjusted" },
  { produto: "KNRI11 — Kinea Renda Imobiliária", emissor: "Kinea Investimentos", categoria: "Equities", subCategoria: "Brick-and-Mortar REIT", geografia: "Brazil", ticker: "KNRI11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.11, retornoUsdPct: 0.018, volatilidadePct: 0.15, fonte: "Kinea REIT dividends + BRL appreciation" },
  { produto: "IVVB11 — iShares S&P 500", emissor: "BlackRock Brasil", categoria: "Equities", subCategoria: "Brazil-Listed S&P 500 ETF", geografia: "Brazil", ticker: "IVVB11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.24, retornoUsdPct: 0.133, volatilidadePct: 0.18, fonte: "SPY in BRL (USD return + BRL depreciation)" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "US Bond ETF", geografia: "USA", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond 10-year average (2015-2025); Bloomberg" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Equities", subCategoria: "US Large-Cap ETF", geografia: "USA", ticker: "SPY", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 10-year average (2015-2025); Bloomberg" },
  { produto: "QUAL — iShares MSCI USA Quality", emissor: "BlackRock", categoria: "Equities", subCategoria: "ETF Quality Factor", geografia: "USA", ticker: "QUAL", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium-High", retornoNativoPct: 0.138, retornoUsdPct: 0.138, volatilidadePct: 0.17, fonte: "MSCI Quality Factor 10-year average; BlackRock" },
  { produto: "IEV — iShares MSCI Europe ETF", emissor: "BlackRock", categoria: "Equities", subCategoria: "Europe Equity ETF", geografia: "Europe", ticker: "IEV", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.075, retornoUsdPct: 0.075, volatilidadePct: 0.18, fonte: "MSCI Europe ETF USD 10-year average" },
  { produto: "IBGX — iShares € Govt Bond UCITS ETF", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "EUR Sovereign", geografia: "Europe", ticker: "IBGX", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Low", retornoNativoPct: 0.015, retornoUsdPct: 0.015, volatilidadePct: 0.06, fonte: "EUR Govt Bond UCITS USD 10-year average" },
];

export const MODEL_P3: PortfolioItemDetail[] = [
  { produto: "U.S. Treasury Note 2Y", emissor: "U.S. Department of Treasury", categoria: "Sovereign Bond", subCategoria: "2-Year T-Note", geografia: "USA", ticker: "USTNT2Y", alocacaoPct: 0.15, valorUsd: 15000, perfilRisco: "Very Low", retornoNativoPct: 0.047, retornoUsdPct: 0.047, volatilidadePct: 0.03, fonte: "Current US T-Note 2Y yield, Jun/2026" },
  { produto: "U.S. Treasury Bond 10Y", emissor: "U.S. Department of Treasury", categoria: "Sovereign Bond", subCategoria: "10-Year T-Bond", geografia: "USA", ticker: "USTNB10", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Very Low", retornoNativoPct: 0.044, retornoUsdPct: 0.044, volatilidadePct: 0.08, fonte: "Current US T-Bond 10Y yield, Jun/2026" },
  { produto: "TLT — iShares 20+ Year Treasury", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "Long-Term Treasury ETF", geografia: "USA", ticker: "TLT", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Low-Medium", retornoNativoPct: 0.02, retornoUsdPct: 0.02, volatilidadePct: 0.14, fonte: "iShares 20+ yr; 10-year return depressed by high rates" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "Broad Bond ETF", geografia: "USA", ticker: "AGG", alocacaoPct: 0.12, valorUsd: 12000, perfilRisco: "Low", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond 10-year average (2015-2025); Bloomberg" },
  { produto: "BND — Vanguard Total Bond Market ETF", emissor: "Vanguard", categoria: "Fixed Income ETF", subCategoria: "Total Bond Market ETF", geografia: "USA", ticker: "BND", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "Vanguard Total Bond 10-year average" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Equities", subCategoria: "Large-Cap ETF", geografia: "USA", ticker: "SPY", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Medium", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 10-year average (2015-2025); Bloomberg" },
  { produto: "IVV — iShares Core S&P 500 ETF", emissor: "BlackRock", categoria: "Equities", subCategoria: "S&P 500 ETF", geografia: "USA", ticker: "IVV", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Medium", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "iShares S&P 500 10-year average" },
  { produto: "VIG — Vanguard Dividend Appreciation ETF", emissor: "Vanguard", categoria: "Equities", subCategoria: "Dividend ETF", geografia: "USA", ticker: "VIG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Medium", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Dividend Appreciation 10-year average; Vanguard" },
  { produto: "QUAL — iShares MSCI USA Quality Factor", emissor: "BlackRock", categoria: "Equities", subCategoria: "ETF Quality Factor", geografia: "USA", ticker: "QUAL", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium-High", retornoNativoPct: 0.138, retornoUsdPct: 0.138, volatilidadePct: 0.17, fonte: "MSCI Quality Factor 10-year average; BlackRock" },
  { produto: "IYR — iShares US Real Estate ETF", emissor: "BlackRock", categoria: "Equities", subCategoria: "US REIT ETF", geografia: "USA", ticker: "IYR", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.085, retornoUsdPct: 0.085, volatilidadePct: 0.20, fonte: "US REITs 10-year average; NAREIT" },
  { produto: "QQQ — Invesco NASDAQ 100 ETF", emissor: "Invesco", categoria: "Equities", subCategoria: "Nasdaq 100 ETF", geografia: "USA", ticker: "QQQ", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium-High", retornoNativoPct: 0.18, retornoUsdPct: 0.18, volatilidadePct: 0.22, fonte: "NASDAQ 100 10-year average (2015-2025)" },
];

export const MODEL_P4: PortfolioItemDetail[] = [
  { produto: "NTN-B 2029", emissor: "Brazilian National Treasury", categoria: "Sovereign Bond", subCategoria: "Tesouro IPCA+", geografia: "Brazil", ticker: "NTNB29", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Very Low", retornoNativoPct: 0.115, retornoUsdPct: 0.025, volatilidadePct: 0.04, fonte: "Historical Tesouro IPCA+; BRL depreciation ~8.5%/yr" },
  { produto: "CDB BTG 120% CDI", emissor: "BTG Pactual", categoria: "Fixed Income", subCategoria: "Floating-Rate CDB", geografia: "Brazil", ticker: "CDB-BTG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low", retornoNativoPct: 0.126, retornoUsdPct: 0.032, volatilidadePct: 0.02, fonte: "120% CDI ~12.6% BRL; FX-adjusted" },
  { produto: "LCI Itaú 2026", emissor: "Itaú BBA", categoria: "Fixed Income", subCategoria: "Floating-Rate LCI", geografia: "Brazil", ticker: "LCI-ITA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Low", retornoNativoPct: 0.095, retornoUsdPct: 0.008, volatilidadePct: 0.01, fonte: "90% CDI, tax-exempt; FX-adjusted" },
  { produto: "Verde Asset FIC FIM", emissor: "Verde Asset Management", categoria: "Multi-Strategy Fund", subCategoria: "Long/Short Macro", geografia: "Brazil", ticker: "VERDE", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Medium-Low", retornoNativoPct: 0.16, retornoUsdPct: 0.064, volatilidadePct: 0.08, fonte: "Verde Asset 10-year CAGR, BRL; FX-adjusted" },
  { produto: "BOVA11", emissor: "BlackRock Brasil", categoria: "Equities", subCategoria: "Brazil Equity ETF", geografia: "Brazil", ticker: "BOVA11.SA", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium", retornoNativoPct: 0.10, retornoUsdPct: 0.008, volatilidadePct: 0.22, fonte: "Ibovespa 10-year average, BRL; FX-adjusted" },
  { produto: "HASH11 — Hashdex Crypto Index", emissor: "Hashdex", categoria: "Equities", subCategoria: "ETF Crypto", geografia: "Brazil", ticker: "HASH11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "High", retornoNativoPct: 0.45, retornoUsdPct: 0.32, volatilidadePct: 0.70, fonte: "Hashdex Crypto Index; high volatility" },
  { produto: "KNRI11 — Kinea Renda Imobiliária", emissor: "Kinea Investimentos", categoria: "Equities", subCategoria: "Brick-and-Mortar REIT", geografia: "Brazil", ticker: "KNRI11.SA", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.11, retornoUsdPct: 0.018, volatilidadePct: 0.15, fonte: "Kinea REIT dividends + BRL appreciation" },
  { produto: "U.S. Treasury Bond 10Y", emissor: "U.S. Department of Treasury", categoria: "Sovereign Bond", subCategoria: "10-Year T-Bond", geografia: "USA", ticker: "USTNB10", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Very Low", retornoNativoPct: 0.044, retornoUsdPct: 0.044, volatilidadePct: 0.08, fonte: "Current US T-Bond 10Y yield, Jun/2026" },
  { produto: "AGG — iShares Core US Aggregate Bond", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "Broad Bond ETF", geografia: "USA", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond 10-year average (2015-2025); Bloomberg" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Equities", subCategoria: "Large-Cap ETF", geografia: "USA", ticker: "SPY", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Medium", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 10-year average (2015-2025); Bloomberg" },
  { produto: "IVV — iShares Core S&P 500 ETF", emissor: "BlackRock", categoria: "Equities", subCategoria: "S&P 500 ETF", geografia: "USA", ticker: "IVV", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "iShares S&P 500 10-year average" },
  { produto: "VIG — Vanguard Dividend Appreciation ETF", emissor: "Vanguard", categoria: "Equities", subCategoria: "Dividend ETF", geografia: "USA", ticker: "VIG", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Dividend Appreciation 10-year average; Vanguard" },
  { produto: "IEV — iShares MSCI Europe ETF", emissor: "BlackRock", categoria: "Equities", subCategoria: "Europe Equity ETF", geografia: "Europe", ticker: "IEV", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.075, retornoUsdPct: 0.075, volatilidadePct: 0.18, fonte: "MSCI Europe ETF USD 10-year average" },
  { produto: "Petrobras USD Bond 2030", emissor: "Petróleo Brasileiro S.A.", categoria: "Eurobond", subCategoria: "Corp Bond USD", geografia: "Brazil", ticker: "PBR2030", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Low-Medium", retornoNativoPct: 0.065, retornoUsdPct: 0.065, volatilidadePct: 0.12, fonte: "Petrobras USD Bond 2030 yield to maturity" },
];

export const MODEL_P5: PortfolioItemDetail[] = [
  { produto: "U.S. Treasury Note 2Y", emissor: "U.S. Treasury", categoria: "Sovereign Bond", subCategoria: "Sovereign Bond", geografia: "Short-Term Sovereign", ticker: "USTNT2Y", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Very Low", retornoNativoPct: 0.047, retornoUsdPct: 0.047, volatilidadePct: 0.03, fonte: "Current US T-Note 2Y yield, Jun/2026" },
  { produto: "U.S. Treasury Bond 10Y", emissor: "U.S. Treasury", categoria: "Sovereign Bond", subCategoria: "Sovereign Bond", geografia: "Long-Term Sovereign", ticker: "USTNB10", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Very Low", retornoNativoPct: 0.044, retornoUsdPct: 0.044, volatilidadePct: 0.08, fonte: "Current US T-Bond 10Y yield, Jun/2026" },
  { produto: "AGG — iShares Core US Aggregate", emissor: "BlackRock", categoria: "Fixed Income ETF", subCategoria: "Fixed Income ETF", geografia: "Bond Broad Market", ticker: "AGG", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Low", retornoNativoPct: 0.025, retornoUsdPct: 0.025, volatilidadePct: 0.05, fonte: "US Agg Bond 10-year average (2015-2025); Bloomberg" },
  { produto: "Apple Inc.", emissor: "Apple Inc.", categoria: "Equities", subCategoria: "Individual Stock", geografia: "Technology — Consumer", ticker: "AAPL", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium-High", retornoNativoPct: 0.25, retornoUsdPct: 0.25, volatilidadePct: 0.25, fonte: "Apple Inc. 10-year average" },
  { produto: "Microsoft Corp.", emissor: "Microsoft Corp.", categoria: "Equities", subCategoria: "Individual Stock", geografia: "Technology — Enterprise", ticker: "MSFT", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium-High", retornoNativoPct: 0.275, retornoUsdPct: 0.275, volatilidadePct: 0.23, fonte: "Microsoft Corp. 10-year average" },
  { produto: "Alphabet Inc. Cl-A", emissor: "Alphabet Inc.", categoria: "Equities", subCategoria: "Individual Stock", geografia: "Technology — Ads/Cloud", ticker: "GOOGL", alocacaoPct: 0.06, valorUsd: 6000, perfilRisco: "Medium-High", retornoNativoPct: 0.18, retornoUsdPct: 0.18, volatilidadePct: 0.25, fonte: "Alphabet Inc. 10-year average" },
  { produto: "JPMorgan Chase & Co.", emissor: "JPMorgan Chase", categoria: "Equities", subCategoria: "Individual Stock", geografia: "Financials — Banking", ticker: "JPM", alocacaoPct: 0.06, valorUsd: 6000, perfilRisco: "Medium-High", retornoNativoPct: 0.15, retornoUsdPct: 0.15, volatilidadePct: 0.22, fonte: "JPMorgan Chase 10-year average" },
  { produto: "Johnson & Johnson", emissor: "J&J", categoria: "Equities", subCategoria: "Individual Stock", geografia: "Healthcare — Diversified", ticker: "JNJ", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.08, retornoUsdPct: 0.08, volatilidadePct: 0.14, fonte: "Johnson & Johnson 10-year average" },
  { produto: "Berkshire Hathaway Cl-B", emissor: "Berkshire Hathaway", categoria: "Equities", subCategoria: "Individual Stock", geografia: "Financials — Conglomerate", ticker: "BRK-B", alocacaoPct: 0.04, valorUsd: 4000, perfilRisco: "Medium-High", retornoNativoPct: 0.13, retornoUsdPct: 0.13, volatilidadePct: 0.18, fonte: "Berkshire Hathaway Cl-B 10-year average" },
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street", categoria: "Equities", subCategoria: "Equity ETF", geografia: "S&P 500 Broad Market", ticker: "SPY", alocacaoPct: 0.10, valorUsd: 10000, perfilRisco: "Medium", retornoNativoPct: 0.133, retornoUsdPct: 0.133, volatilidadePct: 0.17, fonte: "S&P 500 10-year average (2015-2025); Bloomberg" },
  { produto: "QQQ — Invesco NASDAQ-100 ETF", emissor: "Invesco", categoria: "Equities", subCategoria: "Equity ETF", geografia: "Tech / Growth NASDAQ", ticker: "QQQ", alocacaoPct: 0.08, valorUsd: 8000, perfilRisco: "Medium-High", retornoNativoPct: 0.18, retornoUsdPct: 0.18, volatilidadePct: 0.22, fonte: "NASDAQ 100 10-year average (2015-2025)" },
  { produto: "VIG — Vanguard Dividend Appreciation", emissor: "Vanguard", categoria: "Equities", subCategoria: "Equity ETF", geografia: "Dividend Growth", ticker: "VIG", alocacaoPct: 0.07, valorUsd: 7000, perfilRisco: "Medium", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Dividend Appreciation 10-year average; Vanguard" },
  { produto: "VYM — Vanguard High Dividend Yield", emissor: "Vanguard", categoria: "Equities", subCategoria: "Equity ETF", geografia: "High Yield Dividend", ticker: "VYM", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.10, retornoUsdPct: 0.10, volatilidadePct: 0.16, fonte: "High Dividend Yield 10-year average; Vanguard" },
  { produto: "VHT — Vanguard Health Care ETF", emissor: "Vanguard", categoria: "Equities", subCategoria: "Equity ETF", geografia: "Healthcare Sector", ticker: "VHT", alocacaoPct: 0.05, valorUsd: 5000, perfilRisco: "Medium", retornoNativoPct: 0.12, retornoUsdPct: 0.12, volatilidadePct: 0.16, fonte: "Healthcare ETF 10-year average; Vanguard" },
  { produto: "IBIT — iShares Bitcoin Trust ETF", emissor: "BlackRock", categoria: "Crypto ETF", subCategoria: "ETF Crypto", geografia: "Bitcoin — Regulated ETF", ticker: "IBIT", alocacaoPct: 0.02, valorUsd: 2000, perfilRisco: "High", retornoNativoPct: 0.30, retornoUsdPct: 0.30, volatilidadePct: 0.70, fonte: "Bitcoin ETF; 10-year BTC history; high volatility" },
];

export const MODEL_P6: PortfolioItemDetail[] = [
  { produto: "SPY — SPDR S&P 500 ETF", emissor: "State Street Global Advisors", categoria: "Equities", subCategoria: "ETF", geografia: "S&P 500 — 500 largest US companies", ticker: "SPY", alocacaoPct: 1, valorUsd: 100000, perfilRisco: "Medium" },
];

export const MODELS: Record<string, { label: string; subtitle: string; items: PortfolioItemDetail[] }> = {
  P1: { label: "P1 — Conservative Brazil", subtitle: "80% Brazil | 20% US · Conservative Profile", items: MODEL_P1 },
  P2: { label: "P2 — Conservative-Moderate Global", subtitle: "70% Brazil | 20% US | 10% Europe", items: MODEL_P2 },
  P3: { label: "P3 — Conservative US", subtitle: "100% US · Pure USD", items: MODEL_P3 },
  P4: { label: "P4 — Balanced Moderate Global", subtitle: "50% Brazil | 40% US | 10% Europe", items: MODEL_P4 },
  P5: { label: "P5 — Moderate US", subtitle: "100% USD · direct stocks + ETFs + treasuries", items: MODEL_P5 },
  P6: { label: "P6 — Aggressive US", subtitle: "100% S&P 500 (SPY) · benchmark", items: MODEL_P6 },
};
